Added MTU request method
LeandroSQ/android-ble-made-easy pull request #26
Opened 2023-01-16 16:53 UTC by valexi7

I added a method to request MTU change discussed in issue:
MTU size request #25

Usage:
`connection?.requestMTU(512)`

2023-04-12 17:07 UTC, LeandroSQ commented
Hello, thank you for your PR :)
I appreciate it, sorry for the delay, life has been crazy.

Is it possible to remove the files not associated with the change from this PR? e.g .idea folder, or the gradle files.

2023-04-12 17:10 UTC, LeandroSQ requested changes
Awesome work, thank you :)

The only nitpicking is the project-level files.

2023-04-12 17:10 UTC, LeandroSQ commented on .idea/compiler.xml
Is it possible to remove this file from this PR?

2023-04-12 17:10 UTC, LeandroSQ commented on .idea/misc.xml
Is it possible to remove this file from this PR?

2023-04-12 17:10 UTC, LeandroSQ commented on build.gradle
Is it possible to remove this file from this PR?

2023-04-12 17:10 UTC, LeandroSQ commented on gradle/wrapper/gradle-wrapper.properties
Is it possible to remove this file from this PR?

2023-04-12 17:10 UTC, LeandroSQ commented on lib/build.gradle
Is it possible to remove this file from this PR?

2023-04-26 17:51 UTC, karansingla-dev commented
@LeandroSQ  when will you merge this branch? I think when I get large-size data from the BLE device then it disconnected from the Android device.

2023-04-26 18:18 UTC, valexi7 commented
> @LeandroSQ when will you merge this branch? I think when I get large-size data from the BLE device then it disconnected from the Android device.

Hi,
In the meantime you can use this:
https://jitpack.io/#valexi7/android-ble-made-easy

2023-04-26 18:22 UTC, LeandroSQ approved these changes

2023-04-26 18:22 UTC, merged

2023-04-26 18:26 UTC, karansingla007 commented
@valexi7 
this is I am getting

![image](https://user-images.githubusercontent.com/26064126/234668920-f3c02305-3e0b-46d2-9b62-337323a9a8ff.png)

2023-04-26 18:40 UTC, LeandroSQ commented
Some files were deleted on this PR, I reverted the changes and they are on [feature/mtu](https://github.com/LeandroSQ/android-ble-made-easy/tree/feature/mtu) branch. Will create another PR so we can put this into master and plan a new release.

Thank you @valexi7 for this contribution, I appreciate it.

2023-04-26 21:28 UTC, karansingla007 commented
@LeandroSQ where are you planning to merge this branch into the main?

2023-04-26 22:05 UTC, LeandroSQ commented
Yes, tracking on #26

2023-04-27 04:27 UTC, valexi7 commented
> @valexi7 this is I am getting
> 
> ![image](https://user-images.githubusercontent.com/26064126/234668920-f3c02305-3e0b-46d2-9b62-337323a9a8ff.png)

If you have Jitpack implementation it should work like this:

`implementation 'com.github.valexi7:android-ble-made-easy:-SNAPSHOT'`

2023-04-27 15:09 UTC, karansingla-dev commented
@valexi7  See this
![image](https://user-images.githubusercontent.com/26064126/234906048-3a7f9843-4c7d-4350-9116-4eee196761ef.png)